name: (Ubuntu latest gcc) Build and Test
on:
   push:
     tags:
       - "*"
     paths:
       - src/**
       - include/**
     branches: [main]
permissions:
   contents: read

env:
  BUILD_TYPE: Release

jobs:
  build_gcc:
     name: Test build and compilation

     timeout-minutes: 200
     runs-on: ubuntu-latest
     env:
       VCPKG_ROOT: "vcpkg"
       VCPKG_DISABLE_METRICS: "true"

     steps:
       - uses: actions/checkout@v4

       - uses: lukka/get-cmake@latest
       - name: Restore artifacts, setup vcpkg
         uses: lukka/run-vcpkg@v11

       - name: Install build deps
         run: |
           sudo apt-get install libltdl-dev
       - name: Install OpenGL deps
         uses: ./.github/actions/ubuntu_install_opengl_deps

       - name: Update submodules
         run: |
           git rm scenes || true; git submodule update --init --recursive

       - name: Configure
         run: |
           CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
       - name: Build
         run: |
           CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake --build build -j4

       - name: Test run
         run: |
           build/wave_tracer version 1>&2

